### PR TITLE
Update HttpPlugin to return bool to match Magento

### PR DESCRIPTION
**Pull request by MoT3rror**
https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/App/Http.php#L154

### CODE REVIEW

**Comment by IngusSkaistkalns** [comment]
So, can we have a merge here please :)

**Comment by danieluniform** [comment]
I see no problem with this code. Please merge?

**Review by danielmorell — APPROVED** [review]
Hey, sorry about the long wait on this! This looks great!

**Comment by danielmorell** [comment]
This was released in `v1.0.1`.

**Pull request merged**
